language: node_js
node_js:
- '0.12'
env:
  global:
  - GH_REF=github.com/hotosm/oam-uploader-admin.git
  - DEPLOY_BRANCH=master
  - DS_ENV=staging
  - secure: nxqthN76nuNaSRkHAPcgsl9s/PF32wJgYcwQK2/qEb3FTQFw5XKUiyh6Q7/Y9n+W1j1s/1F4DUbaxOZxj5xvoi7pA/cYObQhMIszCjVjXpwQEXuTWHVE3agu6Sm2pVm79hXKaIkiBGu2Gjl1FXYGRTGje0jQXseJgvFhNUwbl6QZw45/hLoBixsm8wLuvgsl5tQ7qLydWmRgEfT0czPaVxSqiYzn8JlpQSzRj7ore6lDNJ5v15GS2IGKoV5Zf2Q8zNwefzTdQacRkb8YVhNbBUPnzJYUod6QMoEmI8xTkOSmMGeb9jD0vKurQo0uxYUbvv/BLOqqPk1zGfWGQ0FdVKi2R0PFAZ62QlrolnYPPZQz9cZaY0OoR8Q9wyVndGPRHv8INjAQOaW+HAc54rIEPZyC+SO6tvWM1Nb2ShgEYbdhyCCbOGvpFvvutCdL4n9SCRMMqI4Mqmjs8VLNu9pC6OOIE3T6RWQ6nw3rJ0h/LzLYDdeq1DLThinhpM14A0JQfE/hBfS3XO89/dNBZAfSFDpNpsTFVxA8JvJxReqjztjZL5kDBL896a3qZnet/X2iTLTj/mMtsvjRb0YGWUDUUHaYEdQal70REJOqaC6BlUVjkGfn2R3IUR8rmnewlU3Q5mR8XSw4rLSEFcfOuw19NSn3Fkj/74tW1LJ+ytPK4Tw=
cache:
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
script:
- npm run build
after_success:
- "./.build_scripts/deploy.sh"
